<?php

use App\Http\Controllers\AbandonedCartController;
use App\Http\Controllers\Admin\BlogController as AdminBlogController;
use App\Http\Controllers\Admin\BookingController as AdminBookingController;
use App\Http\Controllers\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Admin\DeliveryFeeController as AdminDeliveryFeeController;
use App\Http\Controllers\Admin\GalleryController as AdminGalleryController;
use App\Http\Controllers\Admin\LoyaltyController as AdminLoyaltyController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Admin\PageController as AdminPageController;
use App\Http\Controllers\Admin\ProductController as AdminProductController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CouponController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\OrderTrackingController;
use App\Http\Controllers\ProductReviewController;
use App\Http\Controllers\Public\AboutController;
use App\Http\Controllers\Public\BlogController;
use App\Http\Controllers\Public\BookingsPageController;
use App\Http\Controllers\Public\CheckoutPageController;
use App\Http\Controllers\Public\ContactPageController;
use App\Http\Controllers\Public\GalleryPageController;
use App\Http\Controllers\Public\HomeController;
use App\Http\Controllers\Public\LegalPageController;
use App\Http\Controllers\Public\MenuController;
use App\Http\Controllers\RecurringOrderController;
use App\Http\Controllers\StripeWebhookController;
use App\Http\Controllers\UnsubscribeController;
use App\Http\Controllers\UserDashboardController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');
Route::get('/menu', [MenuController::class, 'index'])->name('menu.index');
Route::get('/menu/{product}', [MenuController::class, 'show'])->name('menu.show');
Route::post('/menu/{product}/reviews', [ProductReviewController::class, 'store'])->name('menu.reviews.store');
Route::get('/about', AboutController::class)->name('about');
Route::get('/gallery', GalleryPageController::class)->name('gallery');
Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('/blog/{post:slug}', [BlogController::class, 'show'])->name('blog.show');
Route::get('/contact', ContactPageController::class)->name('contact');
Route::get('/faq', [LegalPageController::class, 'faq'])->name('legal.faq');
Route::get('/privacy-policy', [LegalPageController::class, 'privacy'])->name('legal.privacy');
Route::get('/terms-and-conditions', [LegalPageController::class, 'terms'])->name('legal.terms');
Route::get('/refund-policy', [LegalPageController::class, 'refund'])->name('legal.refund');
Route::post('/contact', [ContactController::class, 'store'])->name('contact.store');
Route::get('/checkout', CheckoutPageController::class)->name('checkout');
Route::post('/orders', [OrderController::class, 'store'])->name('orders.store');
Route::get('/orders/stripe/success', [OrderController::class, 'stripeSuccess'])->name('orders.stripe.success');
Route::get('/orders/stripe/cancel', [OrderController::class, 'stripeCancel'])->name('orders.stripe.cancel');
Route::get('/orders/track/{token}', OrderTrackingController::class)->middleware('throttle:60,1')->name('orders.track');
Route::post('/stripe/webhook', StripeWebhookController::class)->name('stripe.webhook');
Route::get('/bookings', BookingsPageController::class)->name('bookings');
Route::post('/bookings', [BookingController::class, 'store'])->name('bookings.store');
Route::post('/newsletter', [NewsletterController::class, 'store'])->name('newsletter.store');
Route::post('/coupons/validate', [CouponController::class, 'validateCode'])->middleware('throttle:30,1')->name('coupons.validate');
Route::post('/cart/capture', [AbandonedCartController::class, 'capture'])->middleware('throttle:30,1')->name('cart.capture');
Route::get('/cart/recover/{token}', [AbandonedCartController::class, 'recover'])->name('cart.recover');
Route::get('/unsubscribe/{email}', UnsubscribeController::class)->middleware(['signed', 'throttle:20,1'])->name('unsubscribe');
Route::get('/recurring/{recurring}/skip/{date}', [RecurringOrderController::class, 'skipPage'])->middleware(['signed', 'throttle:20,1'])->name('recurring.skip');
Route::post('/recurring/{recurring}/skip/{date}', [RecurringOrderController::class, 'skipConfirm'])->middleware(['signed', 'throttle:20,1'])->name('recurring.skip.confirm');

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('/dashboard', UserDashboardController::class)->name('dashboard');
    Route::get('/dashboard/orders', [UserDashboardController::class, 'orders'])->name('dashboard.orders');
    Route::get('/dashboard/bookings', [UserDashboardController::class, 'bookings'])->name('dashboard.bookings');
    Route::get('/dashboard/points', [UserDashboardController::class, 'points'])->name('dashboard.points');
    Route::get('/dashboard/recurring', [RecurringOrderController::class, 'index'])->name('dashboard.recurring');
    Route::post('/dashboard/recurring/{recurring}/pause', [RecurringOrderController::class, 'pause'])->name('dashboard.recurring.pause');
    Route::post('/dashboard/recurring/{recurring}/resume', [RecurringOrderController::class, 'resume'])->name('dashboard.recurring.resume');
    Route::post('/dashboard/recurring/{recurring}/cancel', [RecurringOrderController::class, 'cancel'])->name('dashboard.recurring.cancel');
    Route::post('/dashboard/recurring/{recurring}/skip', [RecurringOrderController::class, 'skipNext'])->name('dashboard.recurring.skip');
    Route::get('/dashboard/orders/{order}/reorder', [UserDashboardController::class, 'reorder'])->name('dashboard.orders.reorder');
});

Route::middleware(['auth', 'admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/', AdminDashboardController::class)->name('dashboard');
    Route::get('/products', [AdminProductController::class, 'index'])->name('products.index');
    Route::get('/products/create', [AdminProductController::class, 'create'])->name('products.create');
    Route::post('/products', [AdminProductController::class, 'store'])->name('products.store');
    Route::get('/products/{product}/edit', [AdminProductController::class, 'edit'])->name('products.edit');
    Route::put('/products/{product}', [AdminProductController::class, 'update'])->name('products.update');
    Route::delete('/products/{product}', [AdminProductController::class, 'destroy'])->name('products.destroy');
    Route::post('/products/{product}/duplicate', [AdminProductController::class, 'duplicate'])->name('products.duplicate');
    Route::get('/categories', [AdminCategoryController::class, 'index'])->name('categories.index');
    Route::get('/categories/create', [AdminCategoryController::class, 'create'])->name('categories.create');
    Route::post('/categories', [AdminCategoryController::class, 'store'])->name('categories.store');
    Route::get('/categories/{category}/edit', [AdminCategoryController::class, 'edit'])->name('categories.edit');
    Route::put('/categories/{category}', [AdminCategoryController::class, 'update'])->name('categories.update');
    Route::delete('/categories/{category}', [AdminCategoryController::class, 'destroy'])->name('categories.destroy');
    Route::get('/gallery', [AdminGalleryController::class, 'index'])->name('gallery.index');
    Route::post('/gallery', [AdminGalleryController::class, 'store'])->name('gallery.store');
    Route::delete('/gallery/{galleryItem}', [AdminGalleryController::class, 'destroy'])->name('gallery.destroy');
    Route::get('/blogs', [AdminBlogController::class, 'index'])->name('blogs.index');
    Route::get('/blogs/create', [AdminBlogController::class, 'create'])->name('blogs.create');
    Route::post('/blogs', [AdminBlogController::class, 'store'])->name('blogs.store');
    Route::get('/blogs/{blog}/edit', [AdminBlogController::class, 'edit'])->name('blogs.edit');
    Route::put('/blogs/{blog}', [AdminBlogController::class, 'update'])->name('blogs.update');
    Route::delete('/blogs/{blog}', [AdminBlogController::class, 'destroy'])->name('blogs.destroy');
    Route::get('/orders', [AdminOrderController::class, 'index'])->name('orders.index');
    Route::patch('/orders/{order}', [AdminOrderController::class, 'updateStatus'])->name('orders.update-status');
    Route::delete('/orders/{order}', [AdminOrderController::class, 'destroy'])->name('orders.destroy');
    Route::get('/loyalty', [AdminLoyaltyController::class, 'index'])->name('loyalty.index');
    Route::put('/loyalty', [AdminLoyaltyController::class, 'update'])->name('loyalty.update');
    Route::post('/loyalty/adjust', [AdminLoyaltyController::class, 'adjust'])->name('loyalty.adjust');
    Route::get('/coupons', [AdminCouponController::class, 'index'])->name('coupons.index');
    Route::post('/coupons', [AdminCouponController::class, 'store'])->name('coupons.store');
    Route::put('/coupons/welcome-offer', [AdminCouponController::class, 'updateWelcome'])->name('coupons.welcome');
    Route::put('/coupons/winback', [AdminCouponController::class, 'updateWinback'])->name('coupons.winback');
    Route::put('/coupons/{coupon}', [AdminCouponController::class, 'update'])->name('coupons.update');
    Route::delete('/coupons/{coupon}', [AdminCouponController::class, 'destroy'])->name('coupons.destroy');
    Route::get('/delivery-fees', [AdminDeliveryFeeController::class, 'index'])->name('delivery-fees.index');
    Route::post('/delivery-fees', [AdminDeliveryFeeController::class, 'store'])->name('delivery-fees.store');
    Route::put('/delivery-fees/{deliveryFee}', [AdminDeliveryFeeController::class, 'update'])->name('delivery-fees.update');
    Route::delete('/delivery-fees/{deliveryFee}', [AdminDeliveryFeeController::class, 'destroy'])->name('delivery-fees.destroy');
    Route::get('/bookings', [AdminBookingController::class, 'index'])->name('bookings.index');
    Route::patch('/bookings/{booking}', [AdminBookingController::class, 'updateStatus'])->name('bookings.update-status');
    Route::delete('/bookings/{booking}', [AdminBookingController::class, 'destroy'])->name('bookings.destroy');
    Route::get('/pages/{page}', [AdminPageController::class, 'edit'])->name('pages.edit');
    Route::put('/pages/{page}', [AdminPageController::class, 'update'])->name('pages.update');
});

require __DIR__.'/settings.php';
require __DIR__.'/auth.php';
